// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createUserToken = `-- name: CreateUserToken :one
INSERT INTO refresh_tokens (token,created_at,updated_at,user_id, expires_at)

VALUES (


                            $1,
                            now(),
                            now(),
                            $2,
                            $3

)

RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateUserTokenParams struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
}

func (q *Queries) CreateUserToken(ctx context.Context, arg CreateUserTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createUserToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserAndRefreshToken = `-- name: GetUserAndRefreshToken :one
SELECT user_id,token,expires_at,revoked_at FROM refresh_tokens WHERE token = $1
`

type GetUserAndRefreshTokenRow struct {
	UserID    uuid.UUID
	Token     string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

func (q *Queries) GetUserAndRefreshToken(ctx context.Context, token string) (GetUserAndRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getUserAndRefreshToken, token)
	var i GetUserAndRefreshTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now(), updated_at = now() WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, token)
	return err
}
